# Generated by Django 5.2 on 2025-05-10 21:11

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_staticpage_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1200x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='post_images/', verbose_name='Post Görseli'),
        ),
    ]
